## <center><font color='purple'>Building Simple Sequential Classification Model</font></center> 
### <center><font color='green'> Keywords: Keras, classification</font></center>

In [1]:
name = 'Firuz' 
teacher = 'Mandy' # FROM DEEPLIZARD 

useful_links = [
    'https://deeplizard.com', 
    'https://youtube.com/deeplizard' 
]

#### Importing libraries 

In [3]:
import numpy as np 
from random import randint 
from sklearn.utils import shuffle 
from sklearn.preprocessing import MinMaxScaler

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
train_labels = []
train_samples = []

#### Example data:

* An experiemental drug was tested on individulas from age 13 to 100 in clinical trail
* The trail had 2100 participants. Half were under 65 years old, half were 65 years or older
* Around 95% of patients 65 or older experienced side effects.
* Around 95% of patients under 65 experienced no side effects.

In [5]:
for i in range(50): 
    # The ~5% of younger individuals who did experience side effects 
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    # The ~5% of older individuals who did not experience side effects 
    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(0)
    
for i in range(1000): 
    # The ~95% of younger individuals who did not experience side effects 
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    # The ~95% of older individuals who did experience side effects 
    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(1)

In [6]:
train_samples[:10]

[13, 82, 17, 70, 23, 99, 50, 81, 20, 93]

In [7]:
train_labels = np.array(train_labels) 
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

In [8]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [9]:
scaled_train_samples[:10]

array([[0.1954023 ],
       [0.71264368],
       [0.16091954],
       [0.1954023 ],
       [0.7816092 ],
       [0.63218391],
       [0.59770115],
       [0.98850575],
       [0.29885057],
       [0.32183908]])

### Simple Keras Sequential Model 

In [11]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Activation, Dense 
from tensorflow.keras.optimizers import Adam 
from tensorflow.keras.metrics import categorical_crossentropy 
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [14]:
model = Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'), 
    Dense(units=32, activation='relu'), 
    Dense(units=2, activation='softmax')
])

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_4 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [17]:
model.fit(x=scaled_train_samples, y=train_labels, batch_size=10, epochs=30, shuffle=True, verbose=2)

Epoch 1/30
2100/2100 - 0s - loss: 0.6712 - acc: 0.5367
Epoch 2/30
2100/2100 - 0s - loss: 0.6429 - acc: 0.6662
Epoch 3/30
2100/2100 - 0s - loss: 0.6122 - acc: 0.7367
Epoch 4/30
2100/2100 - 0s - loss: 0.5837 - acc: 0.7690
Epoch 5/30
2100/2100 - 0s - loss: 0.5545 - acc: 0.7943
Epoch 6/30
2100/2100 - 0s - loss: 0.5248 - acc: 0.8190
Epoch 7/30
2100/2100 - 0s - loss: 0.4948 - acc: 0.8348
Epoch 8/30
2100/2100 - 0s - loss: 0.4654 - acc: 0.8548
Epoch 9/30
2100/2100 - 0s - loss: 0.4374 - acc: 0.8676
Epoch 10/30
2100/2100 - 0s - loss: 0.4117 - acc: 0.8829
Epoch 11/30
2100/2100 - 0s - loss: 0.3886 - acc: 0.8948
Epoch 12/30
2100/2100 - 0s - loss: 0.3682 - acc: 0.8971
Epoch 13/30
2100/2100 - 0s - loss: 0.3507 - acc: 0.9081
Epoch 14/30
2100/2100 - 0s - loss: 0.3359 - acc: 0.9114
Epoch 15/30
2100/2100 - 0s - loss: 0.3234 - acc: 0.9157
Epoch 16/30
2100/2100 - 0s - loss: 0.3125 - acc: 0.9233
Epoch 17/30
2100/2100 - 0s - loss: 0.3040 - acc: 0.9224
Epoch 18/30
2100/2100 - 0s - loss: 0.2966 - acc: 0.9257
E

### Model Training with Validation

In [18]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

If we set validation_split = 0.1 (10% of train data is validation data now)

In [19]:
model.fit(x=scaled_train_samples, y=train_labels, validation_split=0.1, batch_size=10, epochs=30, shuffle=True, verbose=2)

Train on 1890 samples, validate on 210 samples
Epoch 1/30
1890/1890 - 0s - loss: 0.2582 - acc: 0.9365 - val_loss: 0.2639 - val_acc: 0.9333
Epoch 2/30
1890/1890 - 0s - loss: 0.2569 - acc: 0.9392 - val_loss: 0.2658 - val_acc: 0.9286
Epoch 3/30
1890/1890 - 0s - loss: 0.2560 - acc: 0.9354 - val_loss: 0.2632 - val_acc: 0.9333
Epoch 4/30
1890/1890 - 0s - loss: 0.2552 - acc: 0.9365 - val_loss: 0.2634 - val_acc: 0.9286
Epoch 5/30
1890/1890 - 0s - loss: 0.2544 - acc: 0.9381 - val_loss: 0.2613 - val_acc: 0.9333
Epoch 6/30
1890/1890 - 0s - loss: 0.2535 - acc: 0.9392 - val_loss: 0.2616 - val_acc: 0.9333
Epoch 7/30
1890/1890 - 0s - loss: 0.2529 - acc: 0.9365 - val_loss: 0.2588 - val_acc: 0.9333
Epoch 8/30
1890/1890 - 0s - loss: 0.2523 - acc: 0.9392 - val_loss: 0.2596 - val_acc: 0.9333
Epoch 9/30
1890/1890 - 0s - loss: 0.2513 - acc: 0.9360 - val_loss: 0.2575 - val_acc: 0.9333
Epoch 10/30
1890/1890 - 0s - loss: 0.2509 - acc: 0.9392 - val_loss: 0.2580 - val_acc: 0.9333
Epoch 11/30
1890/1890 - 0s - los

### Creating mock test dataset

In [20]:
test_labels = []
test_samples = []

In [21]:
for i in range(10): 
    # The ~5% of younger individuals who did experience side effects 
    random_younger = randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    # The ~5% of older individuals who did not experience side effects 
    random_older = randint(65, 100)
    test_samples.append(random_older)
    test_labels.append(0)
    
for i in range(200): 
    # The ~95% of younger individuals who did not experience side effects 
    random_younger = randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    # The ~95% of older individuals who did experience side effects 
    random_older = randint(65, 100)
    test_samples.append(random_older)
    test_labels.append(1)

In [22]:
test_labels = np.array(test_labels) 
test_samples = np.array(test_samples)
test_labels, test_samples = shuffle(test_labels, test_samples)

In [23]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

### Predict

In [24]:
predictions = model.predict(x=scaled_test_samples, batch_size=10, verbose=2)

420/420 - 0s


In [26]:
predictions[:10]

array([[0.02380713, 0.9761929 ],
       [0.11570839, 0.88429165],
       [0.9645129 , 0.03548711],
       [0.01577857, 0.98422146],
       [0.01452713, 0.98547286],
       [0.9177162 , 0.08228379],
       [0.9626886 , 0.03731136],
       [0.9695534 , 0.03044664],
       [0.9668923 , 0.03310761],
       [0.01713592, 0.982864  ]], dtype=float32)

In [27]:
rounded_predictions=np.argmax(predictions, axis=-1)

In [28]:
rounded_predictions[:10]

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [30]:
test_labels[:10]

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1])